version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5000:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock